apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: instance55
  namespace: test-ns
spec:
  clusterServiceClassExternalName: redis
  clusterServicePlanExternalName: basic