---
apiVersion: v1
kind: Service
metadata:
  name: go-broker-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80  # Actually use the app via k8s
    targetPort: 8080 # App listeining on this port inside container 
  selector:
    name: go-broker-app