---
apiVersion: v1
kind: Service
metadata:
  name: go-broker-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80  # The port on which we will actually use the app
    targetPort: 8080 
  selector:
    name: go-broker-app